/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package Digital.Innovation.Java;

public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
